framework:
    default_locale: regmel
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - regmel
            - pt-br
            - en
            - es
        providers:
