list:
  path: /
  controller: App\Controller\Web\OrganizationWebController::list
  methods: ['GET']

getOne:
  path: /{id}
  controller: App\Controller\Web\OrganizationWebController::getOne
  methods: ['GET']