controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

regmel_controllers:
    resource:
        path: ../src/Regmel/Controller/
        namespace: App\Regmel\Controller
    type: attribute
