add:
  path: /adicionar
  controller: App\Controller\Web\Admin\ArchitecturalAccessibilityAdminController::add
  methods: ['GET', 'POST']

list:
  path: /
  controller: App\Controller\Web\Admin\ArchitecturalAccessibilityAdminController::list
  methods: ['GET']

remove:
  path: /{id}/remover
  controller: App\Controller\Web\Admin\ArchitecturalAccessibilityAdminController::remove
  methods: ['GET']

edit:
  path: /{id}/editar
  controller: App\Controller\Web\Admin\ArchitecturalAccessibilityAdminController::edit
  methods: ['GET', 'POST']