add:
  path: /adicionar
  controller: App\Controller\Web\Admin\OrganizationAdminController::add
  methods: ['GET', 'POST']

list:
  path: /
  controller: App\Controller\Web\Admin\OrganizationAdminController::list
  methods: ['GET']

get:
  path: /{id}
  controller: App\Controller\Web\Admin\OrganizationAdminController::getOne
  methods: ['GET']

remove:
  path: /{id}/remove
  controller: App\Controller\Web\Admin\OrganizationAdminController::remove
  methods: ['GET']

timeline:
  path: /{id}/timeline
  controller: App\Controller\Web\Admin\OrganizationAdminController::timeline
  methods: ['GET']


invite:
  resource: 'invite.yaml'
  prefix: /{id}/convites
  name_prefix: invite_
  
edit:
  path: /{id}/editar
  controller: App\Controller\Web\Admin\OrganizationAdminController::edit
  methods: ['GET', 'POST']
