create:
  path: /adicionar
  controller: App\Controller\Web\Admin\SpaceTypeAdminController::create
  methods: ['GET', 'POST']

list:
  path: /
  controller: App\Controller\Web\Admin\SpaceTypeAdminController::list
  methods: ['GET']

edit:
  path: /editar/{id}
  controller: App\Controller\Web\Admin\SpaceTypeAdminController::edit
  methods: ['GET', 'POST']
